version: '3'

services:
  app:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db


  db:
    container_name: mongo-db
    image: mongo:4.4
    restart: always
    command: mongod
    ports:
      - "27017:27017"

  
  